databases:
  - name: name_of_your_app
    databaseName: name_of_your_app
    user: name_of_your_app
    plan: free

services:
  - type: web
    plan: free
    name: name_of_your_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: name_of_your_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false